'use strict';
const $=id=>document.getElementById(id), ratios=['free','1:1','3:2','4:3','4:5','16:9','16:10','21:9','1:1.414','1:1.427','1:1.402','custom'],ratioLabels=['自由','1：1（Square）','3：2（35mmフィルム）','4：3（マイクロフォーサーズ、旧TV）','4：5（SNS投稿）','16：9（Youtube、TV）','16：10（PCモニター、ノートPC）','21：9（シネマ）','1：1.414（A/B判）','1：1.427（L判）','1：1.402（2L判）','数値を入力'],orientations={splitRatio:null,collageRatio:null};
for(const id of ['splitRatio','collageRatio']) ratios.forEach((r,i)=>$(id).add(new Option(ratioLabels[i],r)));
let mode='split',source=null,center={x:0,y:0},photos=[],selected=null,tiles=[],drag=null;
let wheelStep=1,wheelReverse=false;
try{const pref=JSON.parse(localStorage.getItem('grid-layout-next-wheel')||'{}');if([1,2,5,10,25].includes(pref.step))wheelStep=pref.step;wheelReverse=pref.reverse===true;}catch{}
function wheelDelta(e){return(e.deltaY<0?1:-1)*wheelStep*(wheelReverse?-1:1);}
for(const id of ['count','rows','gridCols','gridRows'])for(let i=1;i<=5;i++)$(id).add(new Option(i+'枚',i));
$('count').value=2;$('rows').value=1;$('gridCols').value=1;$('gridRows').value=2;
$('splitRatio').value='4:3';$('collageRatio').value='4:3';orientations.splitRatio='portrait';orientations.collageRatio='portrait';
$('layout').value='grid';$('gridControls').hidden=false;$('splitBg').value='#ff0000';$('bgColor').value='#ffffff';
let tileVersion=0;
const canvas=$('preview'),ctx=canvas.getContext('2d');
const ratio=id=>{const value=$(id).value;let parts=(value==='custom'||value==='free')?[+$(id+'Width').value,+$(id+'Height').value]:value.split(':').map(Number);if(parts.some(n=>!Number.isFinite(n)||n<0.01||n>10000)||parts[0]/parts[1]<0.02||parts[0]/parts[1]>50)throw Error('比率は正の数で入力してください（幅÷高さは0.02〜50）。');if(orientations[id]==='portrait')parts.sort((a,b)=>a-b);if(orientations[id]==='landscape')parts.sort((a,b)=>b-a);return parts;};
const status=message=>$('status').textContent=message;
function geometry(){const[a,b]=ratio('splitRatio'),cols=+$('count').value,rows=+$('rows').value,z=+$('splitZoom').value/100,s=Math.min(source.width/(cols*a),source.height/(rows*b))/z,exact=Number.isInteger(a)&&Number.isInteger(b)&&Math.max(a,b)<=32,k=exact?Math.floor(s):s,w=Math.max(1,Math.floor(k*a)),h=Math.max(1,Math.floor(k*b));return{w,h,total:w*cols,height:h*rows,cols,rows,n:cols*rows,x:Math.round(center.x-w*cols/2),y:Math.round(center.y-h*rows/2),imageScale:1};}
function world(){const[a,b]=ratio('collageRatio');return{w:1000,h:1000*b/a};}
function fit(w,h){const box=$('stage').getBoundingClientRect(),s=Math.max(0.001,Math.min((box.width-8)/w,(box.height-8)/h));canvas.width=Math.max(1,Math.round(w*s));canvas.height=Math.max(1,Math.round(h*s));return s;}
function drawPhoto(c,p,factor=1){const {w}=world();c.save();const cell=cellFor(p);if(cell){c.beginPath();c.rect(cell.x*factor,cell.y*factor,cell.w*factor,cell.h*factor);c.clip();}c.translate(p.x*factor,p.y*factor);c.rotate(p.angle*Math.PI/180);const pw=w*p.scale,ph=pw*p.image.height/p.image.width;c.filter=p.blur?'blur('+p.blur*factor+'px)':'none';c.drawImage(p.image,-pw*factor/2,-ph*factor/2,pw*factor,ph*factor);c.restore();}
function outputDimensions(){const long=+$('outputSize').value;if(!Number.isInteger(long)||long<256||long>8192)throw Error('出力の長辺は256〜8192の整数で指定してください。');const[a,b]=ratio('collageRatio'),s=long/Math.max(a,b);return{w:Math.max(1,Math.round(a*s)),h:Math.max(1,Math.round(b*s))};}
function renderUnsafe(){ $('empty').hidden=mode==='split'?!!source:photos.length>0;$('deleteSplit').disabled=!source;ctx.clearRect(0,0,canvas.width,canvas.height);if(mode==='split'){if(!source){canvas.width=1;canvas.height=1;return;}try{const g=geometry();fit(g.total,g.height);drawSplit(ctx,g,canvas.width/g.total);ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=2;drawGrid(g.cols,g.rows,true); $('splitInfo').textContent=`元画像：${source.width} × ${source.height} px\n各タイル：${g.w} × ${g.h} px`;$('makeTiles').disabled=false;}catch(e){$('splitInfo').textContent=e.message;$('makeTiles').disabled=true;}}else{const w=world();fit(w.w,w.h);const f=canvas.width/w.w;ctx.fillStyle=$('bgColor').value;ctx.fillRect(0,0,canvas.width,canvas.height);for(const p of photos)drawPhoto(ctx,p,f);if(isGrid())drawGrid(+$('gridCols').value,+$('gridRows').value);if(selected){const p=selected,pw=w.w*p.scale,ph=pw*p.image.height/p.image.width;ctx.save();ctx.translate(p.x*f,p.y*f);ctx.rotate(p.angle*Math.PI/180);ctx.strokeStyle='#ffc225';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.strokeRect(-pw*f/2,-ph*f/2,pw*f,ph*f);ctx.restore();}drawCenterGuides();try{const d=scaledDimensions(outputDimensions()),up=photos.some(p=>d.w*p.scale>p.image.width+1);$('collageInfo').textContent=`保存サイズ：${d.w} × ${d.h} px\n`;$('saveCollage').disabled=!photos.length||(isGrid()&&photos.length>gridCapacity());if(isGrid()&&photos.length>gridCapacity())$('collageInfo').textContent='写真の枚数が枠数を超えています。行・列を増やすか、写真を削除してください。';}catch(e){$('collageInfo').textContent=e.message;$('saveCollage').disabled=true;}}}
function invalidate(){tileVersion++;for(const t of tiles)URL.revokeObjectURL(t.url);tiles=[];$('tiles').replaceChildren();$('tileResults').hidden=true;}
function updateSplit(){invalidate();$('zoomValue').value=$('splitZoom').value+'%';$('splitAngleValue').value=$('splitAngle').value+'°';render();}
function setMode(next){backToEditor();mode=next;document.querySelectorAll('button[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('splitControls').hidden=mode!=='split';$('collageControls').hidden=mode!=='collage';$('tileResults').hidden=true;render();}
async function decode(file){if(!file.type.startsWith('image/'))throw Error('画像ファイルを選んでください。');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();return image;}finally{URL.revokeObjectURL(url);}}
async function loadFilesImpl(files){try{if(mode==='split'){if(!files.length)return;source=await decode(files[0]);if($('splitRatio').value==='free')setFreeRatio('splitRatio',source.width/+$('count').value,source.height/+$('rows').value);center={x:source.width/2,y:source.height/2};$('splitZoom').value=100;$('splitAngle').value=0;updateSplit();status('写真を読み込みました。ドラッグで切り出し位置を調整できます。');}else{for(const file of files){const image=await decode(file);if(!photos.length&&$('collageRatio').value==='free')setFreeRatio('collageRatio',image.width,image.height);const w=world();const p={image,name:file.name,x:w.w/2+(photos.length%4)*35,y:w.h/2+(photos.length%4)*25,scale:Math.min(.7,.7*w.h/w.w*image.width/image.height),angle:0,blur:0,locked:false,percent:100};p.baseScale=p.scale;p.initial={x:p.x,y:p.y,scale:p.scale};photos.push(p);selected=p;}if(isGrid())arrangeGrid();syncSelection();render();status(`${photos.length}枚の写真を配置しています。`);}}catch(e){status('読み込みできませんでした：'+e.message);}}
function syncSelection(){const list=$('layers');list.replaceChildren();photos.forEach((p,i)=>{const b=document.createElement('button');b.textContent=`${p.locked?"🔒 ":""}${i+1}　${p.name}`;b.classList.toggle('active',p===selected);b.onclick=()=>{selected=p;syncSelection();render();};const row=document.createElement("div");row.className="layer-row";const remove=document.createElement("button");remove.className="remove-layer";remove.textContent="✕";remove.setAttribute("aria-label",p.name+"を削除");remove.onclick=()=>deletePhoto(p);row.append(b,remove);list.append(row);});$('selectedControls').disabled=!selected;if(selected){$('photoScale').value=selected.percent;$('photoScale').disabled=selected.locked;$('photoAngle').disabled=selected.locked;$('photoBlur').disabled=selected.locked;$('resetPhoto').disabled=selected.locked;$('photoLocked').checked=selected.locked;$('photoBlur').value=selected.blur;$('blurValue').value=selected.blur;$('photoAngle').value=selected.angle;$('scaleValue').value=selected.percent+'%';$('angleValue').value=selected.angle+'°';document.querySelectorAll('[data-step=photoScale],[data-step=photoAngle]').forEach(b=>b.disabled=selected.locked);}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};}
canvas.onpointerdown=e=>{if(e.button!==0)return;$('contextMenu').hidden=true;const p=point(e);if(mode==='split'&&source){drag={p,center:{...center},g:geometry()};}else if(mode==='collage'){selected=hitPhoto(p);syncSelection();render();if(selected&&!selected.locked)drag={p,x:selected.x,y:selected.y};}if(drag)canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!drag)return;const p=point(e);if(mode==='split'){const g=drag.g,dx=(p.x-drag.p.x)*g.total/g.imageScale,dy=(p.y-drag.p.y)*g.height/g.imageScale,angle=-+$('splitAngle').value*Math.PI/180;center.x=drag.center.x-dx*Math.cos(angle)+dy*Math.sin(angle);center.y=drag.center.y-dx*Math.sin(angle)-dy*Math.cos(angle);invalidate();render();}else if(selected&&!selected.locked){const w=world();selected.x=drag.x+(p.x-drag.p.x)*w.w;selected.y=drag.y+(p.y-drag.p.y)*w.h;render();}};
canvas.onpointerup=e=>{if(mode==='collage'&&isGrid()&&drag&&selected&&!selected.locked){const p=point(e),cols=+$('gridCols').value,rows=+$('gridRows').value;if(p.x>=0&&p.x<1&&p.y>=0&&p.y<1){const target=Math.floor(p.y*rows)*cols+Math.floor(p.x*cols),own=selected.cell??photos.indexOf(selected);if(target!==own){const other=photos.find(t=>(t.cell??photos.indexOf(t))===target);selected.x=drag.x;selected.y=drag.y;if(other&&!other.locked)swapPhotos(selected,other);else if(!other){const previous=cellFor(selected);selected.cell=target;const next=cellFor(selected);selected.x+=next.x-previous.x;selected.y+=next.y-previous.y;}}}else{selected.x=drag.x;selected.y=drag.y;}}drag=null;syncSelection();render();};canvas.onpointercancel=()=>{if(mode==='collage'&&isGrid()&&drag&&selected){selected.x=drag.x;selected.y=drag.y;}drag=null;render();};
async function blob(c,type='image/png'){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('画像の生成に失敗しました。出力サイズを下げてください。')),type,0.95));}
function download(b,name){const url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('makeTiles').onclick=async()=>{try{invalidate();const version=tileVersion,g=geometry(),original=source;$('makeTiles').disabled=true;for(let i=0;i<g.n;i++){const c=document.createElement('canvas');c.width=g.w;c.height=g.h;drawSplit(c.getContext('2d'),g,1,i%g.cols*g.w,Math.floor(i/g.cols)*g.h);const b=await blob(c);if(version!==tileVersion)return;const url=URL.createObjectURL(b),t={blob:b,url,name:'tile-'+(i+1),checked:true,w:g.w,h:g.h};tiles.push(t);const card=document.createElement('div');card.className='tile';const img=document.createElement('img');img.src=url;img.alt='タイル'+(i+1);const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.onchange=()=>{t.checked=check.checked;$('saveTiles').disabled=!tiles.some(t=>t.checked);};label.append(check,' タイル '+(i+1)+' を保存');const small=document.createElement('small');small.textContent=g.w+' × '+g.h+' px（縮小前）';const save=document.createElement('button');save.className='secondary';save.textContent='この画像を保存';save.onclick=()=>openSave([t]);card.append(img,label,small,save);if(tileHasBackground(g,i%g.cols,Math.floor(i/g.cols))){const warning=document.createElement('p');warning.className='tile-background-notice';warning.textContent='背景色が見えている部分があります。';card.append(warning);}$('tiles').append(card);}$('saveTiles').disabled=false;$('splitBackgroundNotice').hidden=true;showReview('tiles');status('');}catch(e){status(e.message);}finally{render();}};
$('saveTiles').onclick=()=>openSave(tiles.filter(t=>t.checked));
$('saveCollage').onclick=async()=>{try{const w=world(),c=document.createElement('canvas');const f=1000/Math.max(w.w,w.h);c.width=Math.max(1,Math.round(w.w*f));c.height=Math.max(1,Math.round(w.h*f));const cc=c.getContext('2d');cc.fillStyle=$('bgColor').value;cc.fillRect(0,0,c.width,c.height);for(const p of photos)drawPhoto(cc,p,c.width/w.w);if(compositionUrl)URL.revokeObjectURL(compositionUrl);compositionUrl=URL.createObjectURL(await blob(c));$('compositionImage').src=compositionUrl;backgroundNotice('collage');showReview('composition');}catch(e){status(e.message);}};
document.querySelectorAll('button[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('splitFile').onchange=e=>{loadFiles([...e.target.files]);e.target.value='';};$('collageFiles').onchange=e=>{loadFiles([...e.target.files]);e.target.value='';};
for(const id of ['count','rows','splitRatio','splitZoom','splitAngle'])$(id).oninput=updateSplit;
$('splitReset').onclick=()=>{if(source)center={x:source.width/2,y:source.height/2};$('splitZoom').value=100;$('splitAngle').value=0;updateSplit();};
for(const id of ['collageRatio','outputSize','bgColor'])$(id).oninput=()=>{if(id==='collageRatio'&&isGrid())arrangeGrid();render();};
$('photoScale').oninput=()=>{if(selected&&!selected.locked){selected.percent=+$('photoScale').value;selected.scale=selected.baseScale*selected.percent/100;}syncSelection();render();};$('photoAngle').oninput=()=>{if(selected&&!selected.locked)selected.angle=+$('photoAngle').value;syncSelection();render();};$('photoBlur').oninput=()=>{if(selected&&!selected.locked)selected.blur=+$('photoBlur').value;syncSelection();render();};$('photoLocked').onchange=()=>{if(selected)selected.locked=$('photoLocked').checked;syncSelection();render();};
function deletePhoto(p){photos=photos.filter(t=>t!==p);if(selected===p)selected=photos.at(-1)||null;syncSelection();render();commitEdit();}
$('resetPhoto').onclick=()=>{if(!selected||selected.locked)return;const p=selected;if(isGrid()){const c=cellFor(p);p.x=c.x+c.w/2;p.y=c.y+c.h/2;p.baseScale=Math.max(c.w,c.h*p.image.width/p.image.height)/world().w;}else{p.x=p.initial.x;p.y=p.initial.y;p.baseScale=p.initial.scale;}p.percent=100;p.scale=p.baseScale;p.angle=0;p.blur=0;syncSelection();render();};
$('stage').ondragover=e=>{e.preventDefault();};$('stage').ondrop=e=>{e.preventDefault();loadFiles([...e.dataTransfer.files]);};

function isGrid(){return +$('gridCols').value!==1||+$('gridRows').value!==1;}
function gridCapacity(){return +$('gridCols').value*+$('gridRows').value;}
function cellFor(p){if(!isGrid())return null;const i=p.cell??photos.indexOf(p),w=world(),cols=+$('gridCols').value,rows=+$('gridRows').value;return{x:i%cols*w.w/cols,y:Math.floor(i/cols)*w.h/rows,w:w.w/cols,h:w.h/rows};}
function arrangeGrid(){photos.forEach((p,i)=>{p.cell=i;if(p.locked)return;const c=cellFor(p);p.x=c.x+c.w/2;p.y=c.y+c.h/2;p.angle=0;p.baseScale=Math.max(c.w,c.h*p.image.width/p.image.height)/world().w;p.percent=100;p.scale=p.baseScale;});syncSelection();render();}
function drawGrid(cols,rows,numbers=false){ctx.save();ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=2;for(let i=1;i<cols;i++){ctx.beginPath();ctx.moveTo(i*canvas.width/cols,0);ctx.lineTo(i*canvas.width/cols,canvas.height);ctx.stroke();}for(let i=1;i<rows;i++){ctx.beginPath();ctx.moveTo(0,i*canvas.height/rows);ctx.lineTo(canvas.width,i*canvas.height/rows);ctx.stroke();}if(numbers)for(let i=0;i<cols*rows;i++){const x=i%cols*canvas.width/cols+6,y=Math.floor(i/cols)*canvas.height/rows+6;ctx.fillStyle='rgba(24,51,36,.75)';ctx.fillRect(x,y,28,23);ctx.fillStyle='white';ctx.font='12px sans-serif';ctx.fillText(i+1,x+7,y+16);}ctx.restore();}
$('layout').onchange=()=>{$('gridControls').hidden=!isGrid();if(isGrid())arrangeGrid();render();};
for(const id of ['gridCols','gridRows'])$(id).onchange=()=>{$('layout').value=isGrid()?'grid':'free';if(isGrid())arrangeGrid();else{syncSelection();render();}};
$('arrangeGrid').onclick=arrangeGrid;
canvas.addEventListener('wheel',e=>{if(!e.deltaY)return;if(mode==='split'&&source){e.preventDefault();$('splitZoom').value=Math.max(100,Math.min(3000,+$('splitZoom').value+wheelDelta(e)));updateSplit();}else if(mode==='collage'){const p=hitPhoto(point(e));if(!p)return;e.preventDefault();selected=p;if(!p.locked){p.percent=Math.max(10,Math.min(3000,p.percent+wheelDelta(e)));p.scale=p.baseScale*p.percent/100;}syncSelection();render();}},{passive:false});
function scaledDimensions(d,scale=+$('saveScale').value){return{w:Math.max(1,Math.round(d.w*scale)),h:Math.max(1,Math.round(d.h*scale))};}
function saveOptions(){const ext=$('saveFormat').value;return{ext,type:ext==='jpg'?'image/jpeg':'image/png',scale:+$('saveScale').value,choose:pendingSave.length>1?typeof window.showDirectoryPicker==='function':typeof window.showSaveFilePicker==='function'};}
async function encodeItem(item,options){if(!item.composition&&options.ext==='png'&&options.scale===1)return item.blob;const d=scaledDimensions(item.composition?outputDimensions():item,options.scale),c=document.createElement('canvas');c.width=d.w;c.height=d.h;const cc=c.getContext('2d');cc.imageSmoothingQuality='high';if(item.composition){cc.fillStyle=$('bgColor').value;cc.fillRect(0,0,d.w,d.h);for(const p of photos)drawPhoto(cc,p,d.w/world().w);}else{if(options.ext==='jpg'){cc.fillStyle='#fff';cc.fillRect(0,0,d.w,d.h);}const image=await createImageBitmap(item.blob);cc.drawImage(image,0,0,d.w,d.h);image.close();}return blob(c,options.type);}
async function saveItems(items){if(!items.length)return;const stamp=dateName();items=items.map((item,i)=>({...item,name:stamp+(items.length>1?'_'+String(i+1).padStart(2,'0'):'' )}));const options=saveOptions();try{let directory=null,handle=null;if(options.choose){if(items.length>1){if(!window.showDirectoryPicker)throw Error('このブラウザーでは保存先を選択できません。Chrome/Edgeで開くか、通常のダウンロードを選び、ブラウザーの「保存場所を毎回確認する」を有効にしてください。');directory=await window.showDirectoryPicker({mode:'readwrite'});}else{if(!window.showSaveFilePicker)throw Error('このブラウザーでは保存先を選択できません。Chrome/Edgeで開くか、通常のダウンロードを選んでください。');handle=await window.showSaveFilePicker({suggestedName:items[0].name+'.'+options.ext,types:[{description:options.ext.toUpperCase()+'画像',accept:{[options.type]:['.'+options.ext]}}]});}}for(const item of items){const data=await encodeItem(item,options);let file=handle;if(directory){let name=item.name+'.'+options.ext,index=1;while(true){try{await directory.getFileHandle(name);name=item.name+' ('+(index++)+').'+options.ext;}catch(e){if(e.name==='NotFoundError')break;throw e;}}file=await directory.getFileHandle(name,{create:true});}if(file){const stream=await file.createWritable();await stream.write(data);await stream.close();}else{download(data,item.name+'.'+options.ext);await new Promise(r=>setTimeout(r,250));}}status(items.length+'枚の'+options.ext.toUpperCase()+(options.choose?'を選んだ場所に保存しました。':'のダウンロードを開始しました。'));}catch(e){status(e.name==='AbortError'?'保存をキャンセルしました。':'保存できませんでした：'+e.message);}}
function saveHelp(){render();if(pendingSave.length&&$('saveDialog').open)updateSaveSizes();}
for(const id of ['saveFormat','saveScale'])$(id).onchange=saveHelp;
render();
let pendingSave=[],compositionUrl=null;
function dateName(d=new Date()){const p=n=>String(n).padStart(2,'0');return d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+'_'+p(d.getHours())+p(d.getMinutes())+p(d.getSeconds());}
function openSave(items){if(!items.length)return;pendingSave=items;$('saveDialog').showModal();saveHelp();}
$('cancelSave').onclick=()=>$('saveDialog').close();$('confirmSave').onclick=()=>{$('saveDialog').close();saveItems(pendingSave);};
function backToEditor(){document.querySelector('.workspace').hidden=false;$('tileResults').hidden=true;$('compositionReview').hidden=true;requestAnimationFrame(render);}
function showReview(view){document.querySelector('.workspace').hidden=true;$('tileResults').hidden=view!=='tiles';$('compositionReview').hidden=view!=='composition';}
$('backTiles').onclick=$('backComposition').onclick=backToEditor;$('saveComposition').onclick=()=>openSave([{composition:true}]);
function drawSplit(c,g,f=1,offsetX=0,offsetY=0,background=true){c.save();if(background){c.fillStyle=$('splitBg').value;c.fillRect(0,0,c.canvas.width,c.canvas.height);}c.translate((Math.floor(g.total/2)-offsetX)*f,(Math.floor(g.height/2)-offsetY)*f);c.rotate(+$('splitAngle').value*Math.PI/180);c.scale(g.imageScale*f,g.imageScale*f);c.drawImage(source,-Math.round(center.x),-Math.round(center.y));c.restore();}
function hitPhoto(p){const w=world(),x=p.x*w.w,y=p.y*w.h;return [...photos].reverse().find(t=>{const cell=cellFor(t);if(cell&&(x<cell.x||x>cell.x+cell.w||y<cell.y||y>cell.y+cell.h))return false;const a=-t.angle*Math.PI/180,dx=x-t.x,dy=y-t.y;return Math.abs(dx*Math.cos(a)-dy*Math.sin(a))<=w.w*t.scale/2&&Math.abs(dx*Math.sin(a)+dy*Math.cos(a))<=w.w*t.scale*t.image.height/t.image.width/2;})||null;}
const contextDelete=document.createElement('button');contextDelete.id='contextDeletePhoto';contextDelete.textContent='写真を削除';$('contextMenu').append(contextDelete);
let contextTile=null;
contextDelete.onclick=()=>{$('contextMenu').hidden=true;if(contextTile){const index=tiles.indexOf(contextTile);if(index>=0){URL.revokeObjectURL(contextTile.url);tiles.splice(index,1);$('tiles').children[index]?.remove();$('saveTiles').disabled=!tiles.some(t=>t.checked);}contextTile=null;}else if(mode==='split')$('deleteSplit').click();else if(selected)deletePhoto(selected);};
canvas.oncontextmenu=e=>{e.preventDefault();const menu=$('contextMenu');menu.hidden=true;if(mode==='split'){if(!source)return;}else{const hit=hitPhoto(point(e));if(!hit)return;selected=hit;syncSelection();render();}menu.querySelectorAll('[data-order]').forEach(button=>button.hidden=mode!=='collage');menu.hidden=false;menu.style.left=Math.max(0,Math.min(e.clientX,innerWidth-menu.offsetWidth))+'px';menu.style.top=Math.max(0,Math.min(e.clientY,innerHeight-menu.offsetHeight))+'px';};
canvas.addEventListener('pointerdown',e=>{if(e.button!==2)return;e.preventDefault();e.stopImmediatePropagation();contextTile=null;canvas.oncontextmenu(e);},true);
document.addEventListener('contextmenu',e=>{if(e.target===canvas){contextTile=null;e.stopPropagation();canvas.oncontextmenu(e);return;}const card=e.target.closest('#tiles .tile');const row=e.target.closest('#layers .layer-row');if(!card&&!row)return;e.preventDefault();e.stopPropagation();const menu=$('contextMenu');contextTile=null;if(card){contextTile=tiles[Array.from($('tiles').children).indexOf(card)];}else{selected=photos[Array.from($('layers').children).indexOf(row)];syncSelection();render();}menu.querySelectorAll('[data-order]').forEach(button=>button.hidden=!!card);menu.hidden=false;menu.style.left=Math.max(0,Math.min(e.clientX,innerWidth-menu.offsetWidth))+'px';menu.style.top=Math.max(0,Math.min(e.clientY,innerHeight-menu.offsetHeight))+'px';},true);
document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{if(!selected)return;const i=photos.indexOf(selected),type=b.dataset.order;photos.splice(i,1);const j=type==='top'?photos.length:type==='bottom'?0:type==='up'?Math.min(i+1,photos.length):Math.max(i-1,0);photos.splice(j,0,selected);$('contextMenu').hidden=true;syncSelection();render();});
document.addEventListener('pointerdown',e=>{if(!$('contextMenu').contains(e.target)&&e.target!==canvas)$('contextMenu').hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('contextMenu').hidden=true;drag=null;}});


for(const id of ['splitZoom','splitAngle','photoScale','photoAngle']){const input=$(id);input.title='つまみをダブルクリックでリセット';input.addEventListener('dblclick',e=>{e.preventDefault();if(input.disabled||input.closest('fieldset:disabled'))return;input.value=id.includes('Angle')?0:100;input.dispatchEvent(new Event('input',{bubbles:true}));});}
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=e=>{e.preventDefault();const input=$(b.dataset.step);if(input.disabled||input.closest('fieldset:disabled'))return;input.value=Math.max(+input.min,Math.min(+input.max,+input.value+(+b.dataset.delta)));input.dispatchEvent(new Event('input',{bubbles:true}));});
function drawCenterGuides(){if(mode!=='collage'||!drag||!selected)return;const w=world(),cell=cellFor(selected)||{x:0,y:0,w:w.w,h:w.h},f=canvas.width/w.w,tolerance=5/f,cx=cell.x+cell.w/2,cy=cell.y+cell.h/2;ctx.save();ctx.strokeStyle='#e95881';ctx.lineWidth=1.5;ctx.setLineDash([7,4]);if(Math.abs(selected.x-cx)<=tolerance){ctx.beginPath();ctx.moveTo(cx*f,cell.y*f);ctx.lineTo(cx*f,(cell.y+cell.h)*f);ctx.stroke();}if(Math.abs(selected.y-cy)<=tolerance){ctx.beginPath();ctx.moveTo(cell.x*f,cy*f);ctx.lineTo((cell.x+cell.w)*f,cy*f);ctx.stroke();}ctx.restore();}
function swapPhotos(p,q){const c1=cellFor(p),c2=cellFor(q),i=p.cell??photos.indexOf(p),j=q.cell??photos.indexOf(q);p.x+=c2.x-c1.x;p.y+=c2.y-c1.y;q.x+=c1.x-c2.x;q.y+=c1.y-c2.y;p.cell=j;q.cell=i;status('写真を入れ替えました。');}
canvas.ondblclick=()=>{if(mode==='split'&&source)$('splitReset').click();};$('splitBg').oninput=updateSplit;
document.addEventListener('pointerdown',e=>{if(mode==='collage'&&e.target!==canvas&&!e.target.closest('[data-edit-controls],dialog,#contextMenu,#appMenu,.menu-strip')){selected=null;drag=null;syncSelection();render();}});
function backgroundNotice(which){const c=document.createElement('canvas'),cc=c.getContext('2d');if(which==='split'){const g=geometry();c.width=Math.max(1,Math.round(512*g.total/Math.max(g.total,g.height)));c.height=Math.max(1,Math.round(512*g.height/Math.max(g.total,g.height)));cc.scale(c.width/g.total,c.height/g.height);drawSplit(cc,g,1,0,0,false);}else{const w=world();c.width=Math.max(1,Math.round(512*w.w/Math.max(w.w,w.h)));c.height=Math.max(1,Math.round(512*w.h/Math.max(w.w,w.h)));cc.scale(c.width/w.w,c.height/w.h);for(const p of photos)drawPhoto(cc,{...p,cell:p.cell??photos.indexOf(p),blur:0},1);}const data=cc.getImageData(0,0,c.width,c.height).data;let visible=false;for(let i=3;i<data.length;i+=4)if(data[i]<128){visible=true;break;}const notice=$(which==='split'?'splitBackgroundNotice':'collageBackgroundNotice');notice.hidden=!visible;notice.textContent=visible?'背景色が見えている部分があります。':'';return visible;}

function setFreeRatio(id,w,h){const scale=100/Math.max(w,h);$(id+'Width').value=+(w*scale).toFixed(4);$(id+'Height').value=+(h*scale).toFixed(4);}
function ratioChanged(id){$(id+'Inputs').hidden=!['free','custom'].includes($(id).value);try{const[a,b]=ratio(id);$(id+'Orientation').title=(a<b?'縦向き':'横向き')+'：クリックで切り替え';$(id+'Orientation').setAttribute('aria-label',a<b?'横向きに切り替える':'縦向きに切り替える');if(id==='splitRatio')updateSplit();else{if(isGrid())arrangeGrid();render();}}catch(e){status(e.message);if(id==='splitRatio')$('makeTiles').disabled=true;else $('saveCollage').disabled=true;}}
for(const id of ['splitRatio','collageRatio']){$(id).oninput=()=>{orientations[id]=null;ratioChanged(id);};for(const suffix of ['Width','Height'])$(id+suffix).oninput=()=>ratioChanged(id);$(id+'Orientation').onclick=()=>{try{const[a,b]=ratio(id);orientations[id]=a>=b?'portrait':'landscape';ratioChanged(id);}catch(e){status(e.message);}};$(id+'Inputs').hidden=false;}
function render(){if(window.appHasExited)return;try{renderUnsafe();}catch(e){status(e.message);if(mode==='split')$('makeTiles').disabled=true;else $('saveCollage').disabled=true;}}
for(const id of ['splitRatio','collageRatio']){$(id+'Inputs').hidden=true;$(id+'Orientation').title='縦向き：クリックで切り替え';$(id+'Orientation').setAttribute('aria-label','横向きに切り替える');}
let exited=false,sizeVersion=0,undoHistory=[],lastEdit=null,loadingFiles=false;
const ownedUrls=new Set(),nativeCreateUrl=URL.createObjectURL.bind(URL),nativeRevokeUrl=URL.revokeObjectURL.bind(URL);
URL.createObjectURL=value=>{const url=nativeCreateUrl(value);ownedUrls.add(url);return url;};URL.revokeObjectURL=url=>{ownedUrls.delete(url);nativeRevokeUrl(url);};
function editSnapshot(){const values={};document.querySelectorAll('[data-edit-controls] input:not([type=file]),[data-edit-controls] select').forEach(el=>{if(el.closest('#selectedControls'))return;values[el.id]=el.type==='checkbox'?el.checked:el.value;});return{source,center:{...center},photos:photos.map(p=>({...p,initial:{...p.initial}})),selected:selected?photos.indexOf(selected):-1,values,orientations:{...orientations}};}
function sameEdit(a,b){return a&&a.source===b.source&&JSON.stringify(a.values)===JSON.stringify(b.values)&&JSON.stringify(a.orientations)===JSON.stringify(b.orientations)&&JSON.stringify(a.center)===JSON.stringify(b.center)&&a.photos.length===b.photos.length&&a.photos.every((p,i)=>{const q=b.photos[i];return p.image===q.image&&['x','y','scale','angle','blur','locked','percent','cell','baseScale'].every(key=>p[key]===q[key]);});}
function commitEdit(){if(exited||loadingFiles)return;const now=editSnapshot();if(lastEdit&&!sameEdit(lastEdit,now)){undoHistory.push(lastEdit);if(undoHistory.length>30)undoHistory.shift();}lastEdit=now;$('undo').disabled=!undoHistory.length;}
async function loadFiles(files){if(exited)return;loadingFiles=true;try{await loadFilesImpl(files);}finally{loadingFiles=false;commitEdit();}}
$('undo').onclick=()=>{const state=undoHistory.pop();if(!state)return;source=state.source;center={...state.center};photos=state.photos.map(p=>({...p,initial:{...p.initial}}));selected=photos[state.selected]||null;for(const[id,value]of Object.entries(state.values)){const el=$(id);if(el.type==='checkbox')el.checked=value;else el.value=value;}Object.assign(orientations,state.orientations);for(const id of ['splitRatio','collageRatio'])$(id+'Inputs').hidden=!['free','custom'].includes($(id).value);$('gridControls').hidden=!isGrid();invalidate();backToEditor();syncSelection();$('zoomValue').value=$('splitZoom').value+'%';$('splitAngleValue').value=$('splitAngle').value+'°';lastEdit=editSnapshot();$('undo').disabled=!undoHistory.length;render();status('');};
document.addEventListener('input',e=>{if(e.target.closest('[data-edit-controls]'))commitEdit();});document.addEventListener('change',e=>{if(e.target.closest('[data-edit-controls]')&&e.target.type!=='file')commitEdit();});document.addEventListener('click',e=>{if((e.target.closest('[data-edit-controls]')||e.target.closest('[data-order]'))&&!e.target.closest('label.upload')&&!e.target.matches('input[type=file]'))commitEdit();});document.addEventListener('dblclick',e=>{if(e.target===canvas)commitEdit();});document.addEventListener('pointerup',e=>{if(e.target===canvas)commitEdit();});document.addEventListener('wheel',e=>{if(e.target===canvas)commitEdit();},{passive:true});
function fileSizeLabel(bytes){return bytes>=1000000?(bytes/1000000).toFixed(2)+'MB':Math.max(1,Math.round(bytes/1000))+'KB';}
async function updateSaveSizes(){const version=++sizeVersion,items=[...pendingSave],options=saveOptions(),save=$('confirmSave');save.disabled=true;for(const option of $('saveScale').options)option.textContent=Math.round(+option.value*100)+'%（サイズを計算中…）';try{for(const option of $('saveScale').options){const scale=+option.value,d=scaledDimensions(items[0].composition?outputDimensions():items[0],scale);let total=0,first=0;for(const item of items){const data=await encodeItem(item,{...options,scale});if(exited||version!==sizeVersion)return;total+=data.size;if(!first)first=data.size;}option.textContent=Math.round(scale*100)+'%（'+d.w+'×'+d.h+'px　'+fileSizeLabel(first)+(items.length>1?'／合計'+fileSizeLabel(total)+'・'+items.length+'枚':'')+'）';}}catch(e){if(version===sizeVersion)status(e.message);}finally{if(!exited&&version===sizeVersion)save.disabled=false;}}
$('cancelSave').addEventListener('click',()=>{sizeVersion++;pendingSave=[];});$('saveDialog').addEventListener('cancel',()=>{sizeVersion++;pendingSave=[];});
function exitApplication(navigate=true){exited=true;window.appHasExited=true;tileVersion++;sizeVersion++;if($('saveDialog').open)$('saveDialog').close();const images=new Set([source,...photos.map(p=>p.image),...undoHistory.flatMap(s=>[s.source,...s.photos.map(p=>p.image)])]);images.forEach(im=>{if(im)im.src='';});source=null;photos=[];selected=null;drag=null;tiles=[];pendingSave=[];undoHistory=[];lastEdit=null;compositionUrl=null;for(const url of ownedUrls)nativeRevokeUrl(url);ownedUrls.clear();document.querySelectorAll('img').forEach(im=>im.removeAttribute('src'));document.querySelectorAll('input[type=file]').forEach(el=>el.value='');canvas.width=canvas.height=1;document.body.replaceChildren();const message=document.createElement('p');message.textContent='アプリを終了しました。';document.body.append(message);if(navigate){if(window.desktopWindowControl){window.desktopWindowControl('close').catch(()=>{});}else window.close();setTimeout(()=>{if(!window.closed){message.textContent='アプリを終了し、写真と編集履歴を消去しました。このブラウザーでは自動で閉じられないため、Ctrl＋Wでタブを閉じてください。';message.style.cssText='margin:40px;font-size:16px;line-height:1.8';}},300);}}
 $('exitApp').onclick=()=>exitApplication();lastEdit=editSnapshot();
const SETTINGS_KEY='grid-layout-next-startup-v1';
const factorySettings={split:{cols:2,rows:1,bg:'#ff0000',ratio:'4:3',orientation:'portrait',width:3,height:4},collage:{layout:'grid',cols:1,rows:2,bg:'#ffffff',ratio:'4:3',orientation:'portrait',width:3,height:4}};
function validSettings(settings){for(const key of ['split','collage']){const v=settings?.[key];if(!v||![1,2,3,4,5].includes(v.cols)||![1,2,3,4,5].includes(v.rows)||!/^#[0-9a-f]{6}$/i.test(v.bg)||!ratios.includes(v.ratio)||!['portrait','landscape'].includes(v.orientation)||![v.width,v.height].every(n=>Number.isFinite(n)&&n>=0.01&&n<=10000)||v.width/v.height<0.02||v.width/v.height>50)return false;}return ['grid','free'].includes(settings.collage.layout);}
function readSettings(){try{const settings=JSON.parse(localStorage.getItem(SETTINGS_KEY));if(validSettings(settings))return settings;}catch{}return structuredClone(factorySettings);}
for(const prefix of ['s','c']){for(const suffix of ['Cols','Rows'])for(let i=1;i<=5;i++)$(prefix+suffix).add(new Option(i+'枚',i));ratios.forEach((r,i)=>$(prefix+'Ratio').add(new Option(ratioLabels[i],r)));$(prefix+'Ratio').onchange=()=>{$(prefix+'Custom').hidden=!['custom','free'].includes($(prefix+'Ratio').value);};}
function fillSettings(settings){for(const[prefix,key]of [['s','split'],['c','collage']]){const v=settings[key];for(const suffix of ['Cols','Rows','Bg','Ratio','Orientation','Width','Height'])$(prefix+suffix).value=v[suffix.toLowerCase()];$(prefix+'Ratio').onchange();}$('settingLayout').value=settings.collage.layout;$('settingsStatus').textContent='';}
function applyStartup(settings){const s=settings.split,c=settings.collage;$('count').value=s.cols;$('rows').value=s.rows;$('splitBg').value=s.bg;$('gridCols').value=c.cols;$('gridRows').value=c.rows;$('bgColor').value=c.bg;$('layout').value=c.layout;$('gridControls').hidden=c.layout!=='grid';for(const[id,v]of [['splitRatio',s],['collageRatio',c]]){$(id).value=v.ratio;orientations[id]=v.orientation;$(id+'Width').value=v.width;$(id+'Height').value=v.height;$(id+'Inputs').hidden=!['custom','free'].includes(v.ratio);const[a,b]=ratio(id);$(id+'Orientation').title=(a<b?'縦向き':'横向き')+'：クリックで切り替え';$(id+'Orientation').setAttribute('aria-label',a<b?'横向きに切り替える':'縦向きに切り替える');}}
$('settingsButton').onclick=()=>{fillSettings(readSettings());$('settingsDialog').showModal();};$('settingsCancel').onclick=()=>$('settingsDialog').close();$('settingsReset').onclick=()=>fillSettings(structuredClone(factorySettings));
$('settingsForm').onsubmit=e=>{e.preventDefault();const settings={};for(const[prefix,key]of [['s','split'],['c','collage']]){settings[key]={cols:+$(prefix+'Cols').value,rows:+$(prefix+'Rows').value,bg:$(prefix+'Bg').value,ratio:$(prefix+'Ratio').value,orientation:$(prefix+'Orientation').value,width:+$(prefix+'Width').value,height:+$(prefix+'Height').value};}settings.collage.layout=$('settingLayout').value;if(!validSettings(settings)){$('settingsStatus').textContent='幅・高さは正の数で入力してください。幅÷高さは0.02〜50の範囲です。';return;}try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));$('settingsDialog').close();status('起動時の設定を保存しました。次回起動時に反映されます。');}catch{$('settingsStatus').textContent='設定を保存できませんでした。ブラウザーの保存許可を確認してください。';}};
$('deleteSplit').onclick=()=>{if(!source)return;source=null;center={x:0,y:0};drag=null;invalidate();$('splitFile').value='';$('splitZoom').value=100;$('splitAngle').value=0;$('zoomValue').value='100%';$('splitAngleValue').value='0°';$('splitInfo').textContent='';$('makeTiles').disabled=true;commitEdit();render();status('');};
applyStartup(readSettings());lastEdit=editSnapshot();
new ResizeObserver(()=>render()).observe($('stage'));render();



function tileHasBackground(g,col,row){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(512*g.w/Math.max(g.w,g.h)));c.height=Math.max(1,Math.round(512*g.h/Math.max(g.w,g.h)));const cc=c.getContext('2d');cc.scale(c.width/g.w,c.height/g.h);drawSplit(cc,g,1,col*g.w,row*g.h,false);const data=cc.getImageData(0,0,c.width,c.height).data;for(let i=3;i<data.length;i+=4)if(data[i]<128)return true;return false;}



function syncFullscreen(){const active=!!document.fullscreenElement;$('fullscreenToggle').textContent=active?'標準表示':'全画面表示';$('fullscreenToggle').setAttribute('aria-pressed',String(active));requestAnimationFrame(render);}
async function enterFullscreen(startup=false){try{if(!document.documentElement.requestFullscreen||!document.fullscreenEnabled)throw Error('Fullscreen unavailable');await document.documentElement.requestFullscreen();if($('fullscreenStart').open)$('fullscreenStart').close();syncFullscreen();}catch{if(startup)$('fullscreenStart').showModal();else status('この表示環境では全画面に切り替えられません。通常のブラウザーで開き、F11キーをお試しください。');}}
$('fullscreenToggle').onclick=async()=>{if(document.fullscreenElement){try{await document.exitFullscreen();syncFullscreen();}catch{status('標準表示に戻せませんでした。Escキーをお試しください。');}}else await enterFullscreen();};
$('startFullscreen').onclick=()=>{ $('fullscreenStart').close();enterFullscreen();};$('startStandard').onclick=()=>$('fullscreenStart').close();document.addEventListener('fullscreenchange',syncFullscreen);syncFullscreen();window.desktopFullscreen=false;






