'use strict';
const http=require('http'),net=require('net'),path=require('path'),fs=require('fs'),crypto=require('crypto'),{spawn}=require('child_process');
const edge=[process.env['ProgramFiles(x86)'],process.env.ProgramFiles].filter(Boolean).map(p=>path.join(p,'Microsoft/Edge/Application/msedge.exe')).find(p=>fs.existsSync(p));
if(!edge)throw Error('Microsoft Edgeが見つかりません。');
let socket,child,windowId,targetId,nextId=0;const pending=new Map(),key=crypto.randomBytes(24).toString('hex');
function command(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});}
const bridge=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');const u=new URL(req.url,'http://127.0.0.1');if(req.method!=='POST'||u.searchParams.get('key')!==key){res.writeHead(403).end();return;}try{const state=u.searchParams.get('state');if(state==='close'){res.end('OK');await command('Browser.close');shutdown();return;}if(state!=='normal'){res.writeHead(400).end();return;}await command('Browser.setWindowBounds',{windowId,bounds:{windowState:state}});res.end('OK');}catch(e){res.writeHead(500).end('Window operation failed');}});
function shutdown(){bridge.close();if(socket)socket.close();setTimeout(()=>process.exit(0),100).unref();}
async function unusedPort(){return new Promise(resolve=>{const probe=net.createServer();probe.listen(0,'127.0.0.1',()=>{const p=probe.address().port;probe.close(()=>resolve(p));});});}
bridge.listen(0,'127.0.0.1',async()=>{try{const bridgePort=bridge.address().port,debugPort=await unusedPort(),profile=process.env.GRID_APP_PROFILE||path.join(__dirname,'.desktop-profile');const url=require('url').pathToFileURL(path.join(__dirname,'index.html'));url.searchParams.set('desktop','1');url.searchParams.set('bridge',bridgePort);url.searchParams.set('key',key);child=spawn(edge,['--app='+url.href,'--user-data-dir='+profile,'--remote-debugging-port='+debugPort,'--remote-debugging-address=127.0.0.1','--no-first-run','--no-default-browser-check','--disable-background-mode'],{stdio:'ignore'});child.once('exit',shutdown);child.once('error',e=>{console.error(e.message);shutdown();});let metadata;for(let i=0;i<100;i++){try{metadata=await(await fetch('http://127.0.0.1:'+debugPort+'/json/version')).json();break;}catch{await new Promise(r=>setTimeout(r,100));}}if(!metadata)throw Error('Edgeの起動に失敗しました。');socket=new WebSocket(metadata.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});socket.addEventListener('message',e=>{const data=JSON.parse(e.data),task=pending.get(data.id);if(task){pending.delete(data.id);data.error?task.reject(Error(data.error.message)):task.resolve(data.result);}});socket.addEventListener('close',shutdown,{once:true});let targets;for(let i=0;i<100;i++){targets=await command('Target.getTargets');targetId=targets.targetInfos.find(t=>t.type==='page'&&t.url.includes('index.html'))?.targetId;if(targetId)break;await new Promise(r=>setTimeout(r,100));}if(!targetId)throw Error('アプリのウィンドウが見つかりません。');({windowId}=await command('Browser.getWindowForTarget',{targetId}));await command('Browser.setWindowBounds',{windowId,bounds:{windowState:'normal'}});console.log(JSON.stringify({debugPort,bridgePort,windowId,targetId}));}catch(e){console.error(e.message);if(socket?.readyState===1)await command('Browser.close').catch(()=>{});shutdown();}});
