'use strict';
const operationDefaults={rotation:1,move:10,blur:1,splitLimit:3,collageLimit:3};let operationSettings={...operationDefaults};try{Object.assign(operationSettings,JSON.parse(localStorage.getItem('photo-operation-settings')||'{}'));}catch{}
function applyPickerLimits(){tilePickerLimit=Math.max(1,Math.min(5,+operationSettings.splitLimit||3));collagePickerLimit=Math.max(1,Math.min(5,+operationSettings.collageLimit||3));for(const[cells,limit]of [[tileCells,tilePickerLimit],[collageCells,collagePickerLimit]]){cells.style.gridTemplateColumns='repeat('+limit+',1fr)';cells.querySelectorAll('button').forEach(b=>{b.hidden=+b.dataset.col>limit||+b.dataset.row>limit;});}if(+$('count').value>tilePickerLimit||+$('rows').value>tilePickerLimit)chooseTileCount(Math.min(tilePickerLimit,+$('count').value),Math.min(tilePickerLimit,+$('rows').value));if(+$('gridCols').value>collagePickerLimit||+$('gridRows').value>collagePickerLimit)chooseCollageCount(Math.min(collagePickerLimit,+$('gridCols').value),Math.min(collagePickerLimit,+$('gridRows').value));render();}applyPickerLimits();
$('outputSize').closest('label').hidden=true;$('outputSize').closest('label').classList.add('hidden-canvas-size');
const operationDialog=make('dialog','operation-dialog');const operationForm=make('form');operationForm.append(make('h2','','操作設定'));const operationFields={};for(const[key,title,min,max]of [['rotation','回転量（度）',.1,90],['move','移動量（px）',1,500],['blur','ぼかし量',1,50],['splitLimit','分割設定の表示マス数（一辺）',1,5],['collageLimit','結合設定の表示マス数（一辺）',1,5]]){const l=make('label','',title),input=make('input');input.type='number';input.min=min;input.max=max;input.step=key==='rotation'?'.1':'1';input.required=true;l.append(input);operationFields[key]=input;operationForm.append(l);}operationForm.append(make('p','operation-hint','矢印キー：移動 ／ [ ]：回転 ／ − ＋：ぼかし。Shiftで10倍移動。'));const settingsActions=make('div','custom-ratio-actions'),cancel=make('button','secondary','キャンセル'),apply=make('button','primary','適用');cancel.type='button';cancel.onclick=()=>operationDialog.close();apply.type='submit';settingsActions.append(cancel,apply);operationForm.append(settingsActions);operationDialog.append(operationForm);document.body.append(operationDialog);operationForm.onsubmit=e=>{e.preventDefault();for(const[key,input]of Object.entries(operationFields))operationSettings[key]=+input.value;localStorage.setItem('photo-operation-settings',JSON.stringify(operationSettings));applyPickerLimits();operationDialog.close();};
let photoClipboard=null;
function chosenPhotos(){if(mode!=='collage')return [];const items=[...multiplePhotos].filter(p=>photos.includes(p));return items.length?items:selected&&photos.includes(selected)?[selected]:[];}
function copyPhotos(){if(mode==='split'){if(source)photoClipboard={mode:'split',source};}else{const items=chosenPhotos();if(items.length)photoClipboard={mode:'collage',items:items.map(p=>({...p,initial:{...p.initial}}))};}}
function pastePhotos(){if(!photoClipboard)return;if(mode==='collage'){const items=photoClipboard.mode==='collage'?photoClipboard.items:[{image:photoClipboard.source,name:'コピーした写真',x:world().w/2,y:world().h/2,scale:.5,baseScale:.5,percent:100,angle:0,blur:0,locked:false}];multiplePhotos.clear();for(const item of items){const p={...item,x:item.x+operationSettings.move,y:item.y+operationSettings.move,initial:{...(item.initial||{x:item.x,y:item.y,scale:item.scale})}};photos.push(p);multiplePhotos.add(p);selected=p;}multiplePrimary=selected;if(isGrid())arrangeGrid();sizeCanvasFromPhotos();syncSelection();render();commitEdit();}else{const image=photoClipboard.mode==='split'?photoClipboard.source:photoClipboard.items[0].image;source=image;center={x:image.width/2,y:image.height/2};frameSize.value='1';pixelTileWidth.value='0';pixelTileHeight.value='0';updateSplit();commitEdit();}}
function deleteChosen(){if(mode==='split')$('deleteSplit').click();else{const items=chosenPhotos();photos=photos.filter(p=>!items.includes(p));multiplePhotos.clear();selected=photos.at(-1)||null;syncSelection();render();commitEdit();}}
function orderChosen(type){const items=photos.filter(p=>chosenPhotos().includes(p));if(!items.length)return;if(type==='top')photos=[...photos.filter(p=>!items.includes(p)),...items];else if(type==='bottom')photos=[...items,...photos.filter(p=>!items.includes(p))];else{const indices=items.map(p=>photos.indexOf(p)).sort((a,b)=>type==='up'?b-a:a-b);for(const i of indices){const j=i+(type==='up'?1:-1);if(j>=0&&j<photos.length&&!items.includes(photos[j]))[photos[i],photos[j]]=[photos[j],photos[i]];}}syncSelection();render();commitEdit();}
const officeMenu=make('div','office-context-menu');officeMenu.hidden=true;officeMenu.dataset.editControls='';officeMenu.setAttribute('role','menu');document.body.append(officeMenu);
function menuItem(icon,title,action,disabled=false){const b=make('button');b.type='button';b.setAttribute('role','menuitem');b.disabled=disabled;b.append(make('span','menu-icon',icon),make('span','',title));b.onclick=()=>{officeMenu.hidden=true;action();};officeMenu.append(b);}
function openOfficeMenu(e){e.preventDefault();e.stopImmediatePropagation();$('contextMenu').hidden=true;const row=e.target.closest('#layers .layer-row');if(mode==='collage'&&!collagePreviewActive){const p=row?photos[[...layerList.children].indexOf(row)]:e.target===canvas?hitPhoto(point(e)):null;if(p&&!multiplePhotos.has(p)){selected=p;multiplePhotos.clear();multiplePhotos.add(p);multiplePrimary=p;syncSelection();render();}}officeMenu.replaceChildren();const has=mode==='split'?!!source:chosenPhotos().length>0;menuItem('▧','写真選択',()=>$(mode==='split'?'splitFile':'collageFiles').click());menuItem('×','写真削除',deleteChosen,!has);menuItem('▣','コピー　Ctrl+C',copyPhotos,!has);menuItem('▤','貼り付け　Ctrl+V',pastePhotos,!photoClipboard);officeMenu.append(make('hr'));for(const[icon,title,type]of [['↑','最前面へ移動','top'],['↑','前面へ移動','up'],['↓','最背面へ移動','bottom'],['↓','背面へ移動','down']])menuItem(icon,title,()=>orderChosen(type),mode!=='collage'||!has);if(mode==='collage')menuItem('▧','キャンバスの色…',()=>canvasColorDialog.showModal());officeMenu.append(make('hr'));menuItem('⚙','設定…',()=>{for(const[key,input]of Object.entries(operationFields))input.value=operationSettings[key];operationDialog.showModal();});officeMenu.hidden=false;officeMenu.style.left=Math.max(4,Math.min(e.clientX,innerWidth-officeMenu.offsetWidth-4))+'px';officeMenu.style.top=Math.max(4,Math.min(e.clientY,innerHeight-officeMenu.offsetHeight-4))+'px';officeMenu.querySelector('button').focus();}
window.addEventListener('pointerdown',e=>{if(e.button===2&&e.target===canvas)e.stopImmediatePropagation();},true);window.addEventListener('contextmenu',openOfficeMenu,true);document.addEventListener('pointerdown',e=>{if(!officeMenu.contains(e.target))officeMenu.hidden=true;});officeMenu.onkeydown=e=>{const buttons=[...officeMenu.querySelectorAll('button:not(:disabled)')],i=buttons.indexOf(document.activeElement);if(e.key==='Escape'){officeMenu.hidden=true;canvas.focus();}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length].focus();}};
window.addEventListener('keydown',e=>{if(!officeMenu.hidden||splitCropApplied||collagePreviewActive||e.target.closest('input,select,textarea,dialog'))return;if(e.ctrlKey&&(e.key.toLowerCase()==='c'||e.key.toLowerCase()==='v')){e.preventDefault();e.key.toLowerCase()==='c'?copyPhotos():pastePhotos();return;}if(e.key==='Delete'){e.preventDefault();e.stopImmediatePropagation();deleteChosen();return;}const move=operationSettings.move*(e.shiftKey?10:1),items=chosenPhotos().filter(p=>!p.locked);if(mode==='collage'&&items.length){if(e.key.startsWith('Arrow')){for(const p of items){p.x+=e.key==='ArrowRight'?move:e.key==='ArrowLeft'?-move:0;p.y+=e.key==='ArrowDown'?move:e.key==='ArrowUp'?-move:0;}}else if(e.key==='['||e.key===']')for(const p of items)p.angle+=(e.key===']'?1:-1)*operationSettings.rotation;else if(['-','+','='].includes(e.key))for(const p of items)p.blur=Math.max(0,Math.min(50,p.blur+(e.key==='-'?-1:1)*operationSettings.blur));else return;groupBaseline=null;e.preventDefault();syncSelection();render();commitEdit();}else if(mode==='split'&&source){if(e.key.startsWith('Arrow')){center.x+=e.key==='ArrowLeft'?move:e.key==='ArrowRight'?-move:0;center.y+=e.key==='ArrowUp'?move:e.key==='ArrowDown'?-move:0;}else if(e.key==='['||e.key===']')$('splitAngle').value=Math.max(-180,Math.min(180,+$('splitAngle').value+(e.key===']'?1:-1)*operationSettings.rotation));else return;e.preventDefault();updateSplit();commitEdit();}},true);

const noCanvasColor=make('button','no-canvas-color','色なし');noCanvasColor.type='button';noCanvasColor.onclick=()=>{$('canvasNoColor').checked=true;render();commitEdit();};
$('bgColor').addEventListener('input',()=>{$('canvasNoColor').checked=false;render();},true);
const beforeCanvasColorRender=render;render=function(){beforeCanvasColorRender();const transparent=mode==='collage'&&$('canvasNoColor').checked;canvas.classList.toggle('transparent-canvas',transparent);noCanvasColor.classList.toggle('active',$('canvasNoColor').checked);noCanvasColor.setAttribute('aria-pressed',String($('canvasNoColor').checked));};render();

const canvasColorDialog=make('dialog','operation-dialog canvas-color-dialog');canvasColorDialog.append(make('h2','','キャンバスの色'));const colorChoices=make('div','canvas-color-choices');canvasColorDialog.append(noCanvasColor,colorChoices);for(const color of ['#ff0000','#ffffff','#000000','#808080','#ffff00','#0080ff','#00aa60','#ff80c0']){const button=make('button','color-choice');button.style.background=color;button.title=color;button.setAttribute('aria-label',color);button.onclick=()=>{$('bgColor').value=color;$('bgColor').dispatchEvent(new Event('input',{bubbles:true}));canvasColorDialog.close();commitEdit();};colorChoices.append(button);}const customColorLabel=make('label','','その他の色'),customColor=make('input');customColor.type='color';customColor.value=$('bgColor').value;customColor.oninput=()=>{$('bgColor').value=customColor.value;$('bgColor').dispatchEvent(new Event('input',{bubbles:true}));};customColorLabel.append(customColor);const closeColors=make('button','','閉じる');closeColors.onclick=()=>{canvasColorDialog.close();commitEdit();};canvasColorDialog.append(customColorLabel,closeColors);document.body.append(canvasColorDialog);noCanvasColor.onclick=()=>{$('canvasNoColor').checked=true;canvasColorDialog.close();render();commitEdit();};
const canvasColorButton=make('button','canvas-color-selector','キャンバスの色 ▾');canvasColorButton.type='button';canvasColorButton.onclick=()=>{customColor.value=$('bgColor').value;canvasColorDialog.showModal();};bgLabel.hidden=true;bgLabel.classList.add('hidden-canvas-color-input');bgLabel.after(canvasColorButton);collage.querySelectorAll('.color-palette').forEach(p=>p.remove());
persistentAddPhoto.textContent='写真ファイルを選択';
const beforePhotoButtonTextRender=render;render=function(){beforePhotoButtonTextRender();if(mode==='collage'){emptyPhotoButton.replaceChildren(make('span','','写真ファイルを選択'),make('small','join-selection-hint','結合したい写真をすべて選択してください'));}canvasColorButton.classList.toggle('no-color',$('canvasNoColor').checked);};render();

// Start with a single selected cell inside a 3 by 3 picker.
operationSettings.splitLimit=operationSettings.collageLimit=3;
$('count').value=$('rows').value=$('gridCols').value=$('gridRows').value='1';
$('layout').value='free';$('canvasNoColor').checked=true;applyPickerLimits();
collageRatioButtons.querySelector('[data-ratio="free"]')?.remove();
persistentAddPhoto.after(layersHeader);layerEmpty.remove();
for(const button of [$('splitReset'),$('resetPhoto'),quickPreview,canvasColorButton])button.classList.add('matching-preview-button');
const colorDialogHeader=make('div','color-dialog-header');canvasColorDialog.querySelector('h2').before(colorDialogHeader);colorDialogHeader.append(canvasColorDialog.querySelector('h2'));const colorDialogClose=make('button','color-dialog-close','×');colorDialogClose.type='button';colorDialogClose.setAttribute('aria-label','色選択を閉じる');colorDialogClose.onclick=()=>canvasColorDialog.close();colorDialogHeader.append(colorDialogClose);
noCanvasColor.prepend(make('span','transparent-color-icon',''));colorChoices.before(make('p','color-section-caption','標準の色'));const colorDialogFooter=make('div','color-dialog-footer');colorDialogFooter.append(customColorLabel,closeColors);canvasColorDialog.append(colorDialogFooter);closeColors.classList.add('color-dialog-done');
render();commitEdit();

// A click on a ratio button must not activate the first button through its label.
for(const buttons of [ratioButtons,collageRatioButtons])buttons.addEventListener('click',e=>{if(e.target.closest('button'))e.preventDefault();},true);
const layoutLockNotice=make('dialog','operation-dialog');layoutLockNotice.append(make('h2','','配置数を変更できません'),make('p','','写真が固定されています。固定を解除してから配置数を変更してください。'));const closeLockNotice=make('button','primary','OK');closeLockNotice.onclick=()=>layoutLockNotice.close();layoutLockNotice.append(closeLockNotice);document.body.append(layoutLockNotice);
function warnLockedLayout(){if(!layoutLockNotice.open)layoutLockNotice.showModal();}
collageCells.addEventListener('pointerdown',e=>{if(e.button===0&&photos.some(p=>p.locked)){e.preventDefault();e.stopImmediatePropagation();warnLockedLayout();}},true);
collageCells.addEventListener('click',e=>{if(photos.some(p=>p.locked)){e.preventDefault();e.stopImmediatePropagation();warnLockedLayout();}},true);
const chooseBeforeLock=chooseCollageCount;chooseCollageCount=function(cols,rows){if((cols!==+$('gridCols').value||rows!==+$('gridRows').value)&&photos.some(p=>p.locked)){warnLockedLayout();return;}chooseBeforeLock(cols,rows);};
function keepPhotoOnCanvas(p){const w=world(),bounds=cellFor(p)||{x:0,y:0,w:w.w,h:w.h};p.x=Math.max(bounds.x,Math.min(bounds.x+bounds.w,p.x));p.y=Math.max(bounds.y,Math.min(bounds.y+bounds.h,p.y));}
const renderBeforeMovementBounds=render;render=function(){if(mode==='collage')for(const p of photos)if(!p.locked)keepPhotoOnCanvas(p);renderBeforeMovementBounds();};render();

// Preview-only coverage warning; export continues to draw the original photos.
const exposedCanvasWarning=make('div','exposed-canvas-warning','キャンバスが見えています！');exposedCanvasWarning.setAttribute('role','alert');exposedCanvasWarning.hidden=true;$('stage').append(exposedCanvasWarning);
const uncoveredPreviewMask=document.createElement('canvas'),coveragePreview=document.createElement('canvas'),cleanCompositionPreview=document.createElement('canvas');let coverageFlashFrame=0;
function buildUncoveredPreviewMask(){const w=world(),scale=Math.min(1,600/Math.max(canvas.width,canvas.height));coveragePreview.width=Math.max(1,Math.round(canvas.width*scale));coveragePreview.height=Math.max(1,Math.round(canvas.height*scale));const coverageContext=coveragePreview.getContext('2d',{willReadFrequently:true});for(const p of photos)drawPhoto(coverageContext,p,coveragePreview.width/w.w);const pixels=coverageContext.getImageData(0,0,coveragePreview.width,coveragePreview.height);let uncovered=0;for(let i=0;i<pixels.data.length;i+=4){const visible=pixels.data[i+3]<250;pixels.data[i]=255;pixels.data[i+1]=0;pixels.data[i+2]=0;pixels.data[i+3]=visible?180:0;if(visible)uncovered++;}uncoveredPreviewMask.width=coveragePreview.width;uncoveredPreviewMask.height=coveragePreview.height;uncoveredPreviewMask.getContext('2d').putImageData(pixels,0,0);return uncovered>0;}
function flashUncoveredCanvas(time){coverageFlashFrame=0;if(mode!=='collage'||!collagePreviewActive||workspace.hidden||window.appHasExited){exposedCanvasWarning.hidden=true;return;}ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(cleanCompositionPreview,0,0);if(time%1000<500)ctx.drawImage(uncoveredPreviewMask,0,0,canvas.width,canvas.height);coverageFlashFrame=requestAnimationFrame(flashUncoveredCanvas);}
const renderBeforeCoverageWarning=render;render=function(){if(coverageFlashFrame){cancelAnimationFrame(coverageFlashFrame);coverageFlashFrame=0;}renderBeforeCoverageWarning();exposedCanvasWarning.hidden=true;if(mode!=='collage'||!collagePreviewActive||workspace.hidden||!photos.length)return;if(!buildUncoveredPreviewMask())return;cleanCompositionPreview.width=canvas.width;cleanCompositionPreview.height=canvas.height;cleanCompositionPreview.getContext('2d').drawImage(canvas,0,0);exposedCanvasWarning.hidden=false;coverageFlashFrame=requestAnimationFrame(flashUncoveredCanvas);};render();

$('splitRatio').add(new Option('オリジナル','original'));const originalRatioButton=make('button','tile-ratio-button','オリジナル');originalRatioButton.type='button';originalRatioButton.dataset.ratio='original';ratioButtons.prepend(originalRatioButton);
function chooseOriginalRatio(){if(source)center={x:source.width/2,y:source.height/2};$('splitRatio').value='original';orientations.splitRatio=null;frameSize.value='1';pixelTileWidth.value=pixelTileHeight.value='0';$('splitZoom').value='100';$('splitAngle').value='0';splitDisplayReference=null;ratioChanged('splitRatio');syncRatioButtons();}
originalRatioButton.onclick=()=>{chooseOriginalRatio();commitEdit();};const loadBeforeOriginalRatio=loadFilesImpl;loadFilesImpl=async function(files){const previousSource=source;await loadBeforeOriginalRatio(files);if(mode==='split'&&source&&source!==previousSource)chooseOriginalRatio();};
