'use strict';
// Illustrated guide built from local vector artwork; no external resources.
(()=>{
const landscape=(x,y,w,h,tone='#72a9a2')=>`<g transform="translate(${x} ${y})"><rect width="${w}" height="${h}" rx="4" fill="#bfd9df"/><circle cx="${w*.77}" cy="${h*.25}" r="${h*.12}" fill="#ffda71"/><path d="M0 ${h*.7} L${w*.3} ${h*.36} L${w*.62} ${h*.77} L${w} ${h*.45} V${h} H0Z" fill="${tone}"/><path d="M0 ${h*.9} L${w*.54} ${h*.57} L${w} ${h*.94} V${h} H0Z" fill="#315953"/></g>`;
const svg=(title,content,h=240)=>`<svg viewBox="0 0 800 ${h}" role="img" aria-label="${title}" xmlns="http://www.w3.org/2000/svg"><title>${title}</title>${content}</svg>`;
const text=(x,y,t,size=17)=>`<text x="${x}" y="${y}" fill="#eee" font-size="${size}">${t}</text>`;
const splitFigure=svg('1枚の写真を横2枚、縦1枚に分割して別々に保存',landscape(20,36,280,170)+text(20,24,'元の写真')+`<path d="M340 120H415M400 108L415 120L400 132" stroke="#ffc225" stroke-width="4" fill="none"/>`+landscape(460,36,280,170)+`<path d="M600 36V206" stroke="#ffc225" stroke-width="4" stroke-dasharray="8 5"/>`+text(460,24,'横2枚 × 縦1枚')+text(471,230,'タイル1')+text(626,230,'タイル2'));
const collageFigure=svg('複数の写真をグリッド配置、または1列1行で自由配置',`<rect x="20" y="32" width="330" height="182" rx="5" fill="#fff"/>`+landscape(25,37,157,172)+landscape(188,37,157,172,'#b58ba4')+text(20,24,'グリッド配置：横2枚 × 縦1枚')+`<rect x="430" y="32" width="330" height="182" rx="5" fill="#fff"/>`+`<g transform="rotate(-10 530 115)">${landscape(445,58,180,120)}</g><g transform="rotate(12 665 132)">${landscape(569,83,175,117,'#b58ba4')}</g>`+text(430,24,'自由配置：横1枚 × 縦1枚'));
const badge=(x,y,n)=>`<circle cx="${x}" cy="${y}" r="15" fill="#ffc225"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="#171717" font-size="17" font-weight="bold">${n}</text>`;
function controlsFigure(collage){return svg('操作場所の図：左の写真選択、中央の写真、右の配置と調整、右上のプレビュー・保存',`<rect x="12" y="10" width="776" height="300" rx="8" fill="#111" stroke="#555"/><rect x="12" y="10" width="776" height="36" fill="#242424"/>`+text(26,34,'グリッドレイアウト',12)+text(270,34,collage?'写真合成モード':'写真分割モード',13)+`<rect x="26" y="60" width="120" height="42" rx="4" fill="#333"/>`+text(40,87,'写真ファイルを選択',13)+badge(30,65,1)+`<rect x="166" y="56" width="410" height="240" fill="#191919"/>`+landscape(193,70,354,210)+badge(208,88,3)+`<rect x="601" y="58" width="170" height="36" rx="4" fill="#493912"/>`+text(613,82,'プレビュー・保存',13)+badge(757,61,4)+`<rect x="601" y="108" width="170" height="80" rx="5" fill="#292929"/>`+text(613,133,collage?'配置方法':'分割・比率',13)+text(613,159,'横（列）　縦（行）',12)+badge(757,120,2)+`<rect x="601" y="200" width="170" height="91" rx="5" fill="#292929"/>`+text(613,223,'写真の大きさ・回転',12)+text(613,248,collage?'ぼかし・固定':'リセット・背景色',12)+text(26,135,collage?'写真一覧':'写真を削除',13)+text(26,160,collage?'選択・✕で削除':'',12),325);}
const step=(n,title,body)=>`<li><span class="guide-step-number">${n}</span><div><h3>${title}</h3><p>${body}</p></div></li>`;
const editingTips=`<div class="guide-operation-grid"><div><h3>移動</h3><p>写真を押したままドラッグします。</p></div><div><h3>大きさ</h3><p>写真上のホイール、または「写真の大きさ」で調整します。−／＋は1％ずつです。</p></div><div><h3>回転</h3><p>スライダー、または−／＋で1度ずつ調整します。大きさ・回転のつまみをダブルクリックすると、その項目をリセットします。</p></div><div><h3>背景色・比率</h3><p>空白部分の色を選べます。比率選択の右のボタンで縦向き・横向きを切り替えます。</p></div></div>`;
const saveSteps=`<div class="guide-save-flow"><span>保存ボタン</span><b>→</b><span>PNG／JPG</span><b>→</b><span>保存時のサイズ</span><b>→</b><span>保存場所</span></div><p>保存時のサイズは100％・75％・50％・25％から選びます。幅・高さの両方に適用され、画素数と生成したファイル容量を表示します。例えば1000×800pxの写真を50％にすると500×400pxになります。保存名は日時で自動設定されます。</p><p>1枚なら保存先のファイル、複数タイルなら保存先のフォルダーを選びます。保存先選択に対応しない環境では通常のダウンロードになります。</p>`;
const oldBack=helpScreen.querySelector('button');
helpScreen.replaceChildren(oldBack);
const content=document.createElement('div');content.className='illustrated-guide';content.innerHTML=`
<h1>グリッドレイアウトの使い方</h1><p class="guide-lead">写真を分ける。写真を組み合わせる。目的に合わせて2つのモードを使います。</p>
<nav class="guide-toc" aria-label="ヘルプの目次"><a href="#guide-intro">はじめに</a><a href="#guide-split">分割モードとは</a><a href="#guide-collage">合成モードとは</a><a href="#guide-split-steps">分割の操作手順</a><a href="#guide-collage-steps">合成の操作手順</a><a href="#guide-settings">設定・よくある質問</a></nav>
<article id="guide-intro"><h2>はじめに</h2><p>グリッドレイアウトは、1枚の写真を複数の画像に分割したり、複数の写真を1枚の画像に組み合わせたりするアプリです。完成した画像はPNGまたはJPGで保存できます。</p><div class="guide-operation-grid"><div><h3>1枚を分割したい</h3><p>「写真分割モード」を選びます。各タイルを別々の画像として保存します。</p></div><div><h3>複数枚を組み合わせたい</h3><p>「写真合成モード」を選びます。キャンバス全体を1枚の画像として保存します。</p></div></div></article>
<article id="guide-split"><h2>「写真分割モード」とは</h2><p>1枚の写真に格子を重ね、各枠を別の画像として切り出します。横（列）と縦（行）はそれぞれ1～5枚、最大25枚まで指定できます。</p><figure>${splitFigure}<figcaption>横2枚 × 縦1枚の例。黄色の線で区切った左右の部分を、それぞれ保存します。</figcaption></figure><p>「各タイルの比率」は、切り出した1枚ごとの形を決めます。写真全体の比率ではありません。</p></article>
<article id="guide-collage"><h2>「写真合成モード」とは</h2><p>複数の写真をキャンバス上に配置して、1枚の画像にまとめます。整列したレイアウトにも、写真を重ねたレイアウトにもできます。</p><figure>${collageFigure}<figcaption>左：グリッドで整列。右：自由な位置・大きさ・角度で重ねる。</figcaption></figure><p class="guide-important">横（列）1枚 × 縦（行）1枚に設定すると、写真を自由に配置できます。</p><p>それ以外の行・列の組み合わせではグリッド配置になります。「キャンバスの比率」は、保存する画像全体の形を決めます。</p></article>
<article id="guide-split-steps"><h2>「写真分割モード」の操作手順</h2><figure>${controlsFigure(false)}<figcaption>番号順に、写真の選択 → 分割設定 → 調整 → プレビューへ進みます。</figcaption></figure><ol class="guide-steps">
${step(1,'写真ファイルを選択','上段で「写真分割モード」を選び、左の「写真ファイルを選択」で1枚読み込みます。中央への画像ファイルのドロップでも読み込めます。「写真を削除」で読み込んだ写真を外せます。')}
${step(2,'分割する枚数と形を決める','右の「分割・比率」で横（列）・縦（行）の枚数と各タイルの比率を選びます。「数値を入力」で独自の比率も指定できます。中央の白い線が分割位置です。')}
${step(3,'写真を調整','ドラッグで切り出し位置を移動し、大きさ・回転・背景色を調整します。大きさは100～3000％です。中央の写真をダブルクリック、または「リセット」で位置・大きさ・回転を戻します。')}
${step(4,'プレビュー・保存','右上の「プレビュー・保存」を押します。保存するタイルのチェックを選び、「選択したタイルを保存」を押します。「この画像を保存」で1枚だけ保存することもできます。「戻る」で編集を続けられます。')}
</ol>${editingTips}${saveSteps}</article>
<article id="guide-collage-steps"><h2>「写真合成モード」の操作手順</h2><figure>${controlsFigure(true)}<figcaption>左で写真を選び、中央で配置、右で設定してからプレビューします。</figcaption></figure><ol class="guide-steps">
${step(1,'写真ファイルを選択','上段で「写真合成モード」を選び、左の「写真ファイルを選択」で複数の写真を読み込みます。繰り返して追加できます。写真一覧をクリックして編集対象を選び、名前の右の✕で削除します。')}
${step(2,'配置方法とキャンバスを決める','横1枚 × 縦1枚で自由配置になります。それ以外はグリッド配置です。グリッドでは写真の枚数以上の枠を用意してください。「写真を並べ直す」で再整列します。キャンバスの比率・向き、保存画像の長い辺（px）を指定します。')}
${step(3,'各写真を調整','写真を選び、ドラッグで移動、ホイールで拡大・縮小します。大きさは10～3000％、ぼかしは0～50です。グリッドでは別の写真の枠へドラッグして放すと交換します。同じ枠の中では切り出し位置を調整できます。')}
${step(4,'プレビュー・保存','右上の「プレビュー・保存」で完成画像を確認します。「戻る」で編集を続け、「保存」で形式・サイズ・保存先を選びます。写真合成ではキャンバス全体を1枚として保存します。')}
</ol>${editingTips}<div class="guide-operation-grid"><div><h3>写真を固定</h3><p>チェックすると移動・拡大縮小・回転などの調整を止めます。再編集するときは固定を解除してください。</p></div><div><h3>重なり順</h3><p>中央の写真を右クリックし、「最前面へ移動」「前面へ移動」「最背面へ移動」「背面へ移動」から選びます。</p></div><div><h3>リセット</h3><p>固定を解除して「リセット」を押すと、位置・大きさ・回転・ぼかしを戻します。グリッドでは現在の枠に合う大きさに戻ります。</p></div><div><h3>中心線</h3><p>移動中に中心が近づくと補助線が出ます。自由配置ではキャンバス、グリッドでは各枠の中心が目安です。保存画像には入りません。</p></div></div>${saveSteps}</article>
<article id="guide-settings"><h2>設定・よくある質問</h2><details open><summary>プレビュー画面でも写真を動かせますか？</summary><p>ドラッグで表示位置、ホイールで表示倍率を変えられます。ダブルクリックで表示を元に戻します。これは確認用の操作です。保存画像の配置を変える場合は「戻る」で編集画面に戻って調整してください。</p></details><details><summary>背景色の警告はどういう意味ですか？</summary><p>写真が覆っていない部分や透明な部分があり、選んだ背景色が見えています。意図した余白ならそのまま保存できます。余白をなくす場合は編集画面で位置・大きさ・回転を調整してください。</p></details><details><summary>ホイールが細かすぎる・速すぎるときは？</summary><p>右上の歯車で「ホイール1回の拡大・縮小率」を1・2・5・10・25％から選びます。方向の反転もできます。編集画面とプレビューの両方に反映されます。</p></details><details><summary>PNGとJPGはどう違いますか？</summary><p>PNGは画質を劣化させずに圧縮します。JPGは容量を抑えるために画質が変化します。写真用途ではJPG、画質を保ちたい場合はPNGを選べます。</p></details><details><summary>保存画像の長い辺とは？</summary><p>写真合成の出力画像の縦・横のうち、長い方の画素数です。例えば4:3の横向きで3000pxなら3000×2250px、縦向きなら2250×3000pxです。保存時のサイズを50％にすると、さらに幅・高さが半分になります。</p></details><details><summary>設定・終了について</summary><p>歯車の「起動時の配置・比率・背景色…」で初期設定を保存できます。アプリは標準表示で使用します。×は読み込んだ画像と編集履歴を解放して終了します。保存済みの画像は削除しません。未保存の編集内容は再読み込みや終了で失われます。</p></details></article>`;
helpScreen.append(content);
content.querySelectorAll('.guide-toc a').forEach(a=>a.onclick=e=>{e.preventDefault();content.querySelector(a.getAttribute('href')).scrollIntoView({behavior:'smooth',block:'start'});});
})();
